Controllers/PurchasesController.cs
using System.Security.Cryptography.X509Certificates;
using Microsoft.AspNetCore;
using DTPMBanQuanAo.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace DTPMBanQuanAo.Controllers
{
    public class PurchasesController : Controller
    {
        private readonly AppDBContext _context;
        public PurchasesController(AppDBContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Create(){
            ViewBag.SanPham = new SelectList(_context.SanPham, "Id", "Ten"); 
            ViewBag.TaiKhoan = new SelectList(_context.TaiKhoan.Where(p=>p.IdLoaiTK == 3), "Id", "Name"); 
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(PurchasesModel purchasesModel)
        {
            var purchases = purchasesModel.PhieuNhapKho;
            var purchasesDetail = purchasesModel.ChiTietPNK;
            DateTime date = DateTime.Now;
            var createPurchasesDetail = 0;
            purchases.NgayNhap = date;
            if(ModelState.IsValid){
                _context.Add(purchases);
                var createPurchases = await _context.SaveChangesAsync();
                if(createPurchases > 0)
                {
                    var purchasesTemp = await _context.PhieuNhapKho.FirstOrDefaultAsync(p=> p.NgayNhap.Equals(date));
                    int IdPurchases = purchasesTemp.Id;
                    purchasesDetail.PhieuNhapKhoId = IdPurchases;
                    purchasesDetail.TongTienMuc = purchasesDetail.SoLuong * purchasesDetail.DonGiaNhap;
                    _context.Add(purchasesDetail);
                    createPurchasesDetail= await _context.SaveChangesAsync();
                }
                if(createPurchasesDetail > 0)
                {
                    var product = _context.SanPham.FirstOrDefault(p => p.Id == purchasesDetail.SanPhamId);
                    if(product == null){
                        return NotFound();
                    }
                    product.SoLuong += purchasesDetail.SoLuong;
                    if(product.DonGiaNhap == 0)
                    {
                        product.DonGiaNhap = purchasesDetail.DonGiaNhap;
                    }
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
            }

            return View(purchasesModel);
        }
    }
}

Views/Purchases/Create.cshtml
@model DTPMBanQuanAo.Models.PurchasesModel;
@{
    Layout ="~/Views/Shared/_Layout.cshtml";
}
<form asp-controller="Purchases" asp-action="Create" id="form" enctype="multipart/form-data" method="post" >
    <div class="row">
        <div class="col-md-9">
            <div class="form-group">
                <label asp-for="PhieuNhapKho.NhanVienId" class="control-label"></label>
                <select asp-for="PhieuNhapKho.NhanVienId" class="form-control" asp-items="ViewBag.TaiKhoan"></select>
                <span asp-validation-for="PhieuNhapKho.NhanVienId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhieuNhapKho.MoTa" class="control-label"></label>
                <textarea rows="5" asp-for="PhieuNhapKho.MoTa" class="form-control" placeholder="Nhập mô tả sản phẩm"></textarea>
                <span asp-validation-for="PhieuNhapKho.MoTa" class="text-danger"></span>
            </div>
            <div class="form-group-ctpnk editorRows">
                <div class="dongia col-md-3">
                    <label asp-for="ChiTietPNK.DonGiaNhap" class="control-label"></label>
                    <input asp-for="ChiTietPNK.DonGiaNhap" class="form-control" placeholder="Nhập giá nhập" />
                    <span asp-validation-for="ChiTietPNK.DonGiaNhap" class="text-danger"></span>
                </div>
                <div class="soluong col-md-3">
                    <label asp-for="ChiTietPNK.SoLuong" class="control-label"></label>
                    <input asp-for="ChiTietPNK.SoLuong" type="number" min="1" class="form-control" />
                    <span asp-validation-for="ChiTietPNK.SoLuong" class="text-danger"></span>
                </div>
                <div class="sanphamid col-md-3">
                    <label asp-for="ChiTietPNK.SanPhamId" class="control-label"></label>
                    <select asp-for="ChiTietPNK.SanPhamId" class="form-control" asp-items="ViewBag.SanPham"></select>
                </div>
                <div class="trangthai col-md-3">
                    <label asp-for="PhieuNhapKho.TrangThai" class="control-label"></label>
                    <select class="form-select" aria-label="Default select example">
                        <option value="0">Đã thanh toán</option>
                        <option value="1">Chưa thanh toán</option>
                    </select>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                <input type="submit" value="Tạo phiếu nhập" class="btn btn-primary" />
            </div>
        </div>
    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />

}

Views/Purchases/Index.cshtml
Them thanh cong